"""
Mineral Formulas Database
=========================

This file contains chemical formulas for common minerals.
Format: 'Mineral Name': 'Chemical Formula'

Add new minerals by following the existing pattern.
The dictionary is case-insensitive for lookups.

Note: Some minerals have complex or variable formulas, indicated by 'Complex' or 'Variable'.
"""

# =============================================
# NATIVE ELEMENTS
# =============================================
NATIVE_ELEMENTS = {
    # Metals

    'Aluminium': 'Al',
    'Antimon': 'Sb',
    'Arsen': 'As',
    'Bismut': 'Bi',
    'Blei': 'Pb',
    'Chrom': 'Cr',
    'Cobalt': 'Co',
    'Eisen': 'Fe',
    'Elektrum': '(Au,Ag)',
    'Gold': 'Au',
    'Iridium': 'Ir',
    'Kupfer': 'Cu',
    'Mangan': 'Mn',
    'Nickel': 'Ni',
    'Osmium': 'Os',
    'Palladium': 'Pd',
    'Platin': 'Pt',
    'Quecksilber': 'Hg',
    'Rhodium': 'Rh',
    'Ruthenium': 'Ru',
    'Selen': 'Se',
    'Silber': 'Ag',
    'Silizium': 'Si',
    'Tellur': 'Te',
    'Titan': 'Ti',
    'Vanadium': 'V',
    'Wismut': 'Bi',
    'Zink': 'Zn',
    'Zinn': 'Sn',
    # Non-metals
    'Diamant': 'C',
    'Graphit': 'C',
    'Kohlenstoff': 'C',
    'Schwefel': 'S₈',
}

# =============================================
# OXIDES & HYDROXIDES
# =============================================
OXIDES_HYDROXIDES = {
    'Anatas': 'TiO₂',
    'Andalusit': 'Al₂SiO₅',
    'Baddeleyit': 'ZrO₂',
    'Beryll': 'Be₃Al₂(SiO₃)₆',
    'Bismit': 'Bi₂O₃',
    'Braunit': 'Mn₂O₃',
    'Brookit': 'TiO₂',
    'Brucit': 'Mg(OH)₂',
    'Böhmit': 'γ-AlO(OH)',
    'Chromit': 'FeCr₂O₄',
    'Chrysoberyll': 'BeAl₂O₄',
    'Columbit': '(Fe,Mn)(Nb,Ta)₂O₆',
    'Cryptophan': '(Ba,H₂O)₂Mn₅O₁₀',
    'Cuprit': 'Cu₂O',
    'Diaspor': 'α-AlO(OH)',
    'Fergusonit': 'Y(Nb,Ta)O₄',
    'Gibbsit': 'Al(OH)₃',
    'Goethit': 'FeO(OH)',
    'Granat': 'X₃Y₂(SiO₄)₃',
    'Hollandit': 'Ba(Mn⁴⁺,Mn²⁺)₈O₁₆',
    'Hämatit': 'Fe₂O₃',
    'Ilmenit': 'FeTiO₃',
    'Kassiterit': 'SnO₂',
    'Korund': 'Al₂O₃',
    'Kyanit': 'Al₂SiO₅',
    'Limonit': 'FeO(OH)·nH₂O',
    'Magnetit': 'Fe₃O₄',
    'Mikrolith': '(Ca,Na)₂Ta₂O₆(O,OH,F)',
    'Perovskit': 'CaTiO₃',
    'Psilomelan': '(Ba,H₂O)₂Mn₅O₁₀',
    'Pyrochlor': '(Ca,Na)₂(Nb,Ta)₂O₆(O,OH,F)',
    'Pyrolusit': 'MnO₂',
    'Quarz': 'SiO₂',
    'Romanechit': '(Ba,H₂O)₂Mn₅O₁₀',
    'Rutil': 'TiO₂',
    'Samarskit': '(Y,Fe,U)(Nb,Ta)O₄',
    'Sillimanit': 'Al₂SiO₅',
    'Spinell': 'MgAl₂O₄',
    'Staurolith': 'Fe₂Al₉O₆(SiO₄)₄(O,OH)₂',
    'Tantalit': '(Fe,Mn)(Nb,Ta)₂O₆',
    'Topas': 'Al₂SiO₄(F,OH)₂',
    'Uraninit': 'UO₂',
    'Valentinit': 'Sb₂O₃',
    'Zirkon': 'ZrSiO₄',
}

# =============================================
# SULFIDES & SULFOSALTS
# =============================================
SULFIDES = {
    'Aguilarit': 'Ag₄SeS',
    'Akanthit': 'Ag₂S',
    'Antimonit': 'Sb₂S₃',
    'Argentit': 'Ag₂S',
    'Arsenopyrit': 'FeAsS',
    'Auripigment': 'As₂S₃',
    'Berzelianit': 'Cu₂Se',
    'Bornit': 'Cu₅FeS₄',
    'Boulangerit': 'Pb₅Sb₄S₁₁',
    'Bournonit': 'PbCuSbS₃',
    'Breithauptit': 'NiSb',
    'Calaverit': 'AuTe₂',
    'Carrollit': 'CuCo₂S₄',
    'Chalkopyrit': 'CuFeS₂',
    'Chalkosin': 'Cu₂S',
    'Chloanthit': 'NiAs₂',
    'Cinnabarit': 'HgS',
    'Clausthalit': 'PbSe',
    'Cobaltit': 'CoAsS',
    'Coloradoit': 'HgTe',
    'Covellin': 'CuS',
    'Domeykit': 'Cu₃As',
    'Enargit': 'Cu₃AsS₄',
    'Eukairit': 'AgCuSe',
    'Freieslebenit': 'AgPbSbS₃',
    'Frohbergit': 'FeTe₂',
    'Galenit': 'PbS',
    'Gersdorffit': 'NiAsS',
    'Greenockit': 'CdS',
    'Guadalcazarit': 'Pb₆Cu₆Bi₅S₁₈',
    'Jamesonit': 'Pb₄FeSb₆S₁₄',
    'Krennerit': 'AuTe₂',
    'Linnaeit': 'Co₃S₄',
    'Löllingit': 'FeAs₂',
    'Markasit': 'FeS₂',
    'Maucherit': 'Ni₁₁As₈',
    'Melonit': 'NiTe₂',
    'Miargyrit': 'AgSbS₂',
    'Molybdänit': 'MoS₂',
    'Nagyagit': 'Pb₅Au(Sb,Bi)₄S₅-₈',
    'Naumannit': 'Ag₂Se',
    'Nickelin': 'NiAs',
    'Orpiment': 'As₂S₃',
    'Pearceit': '(Ag,Cu)₁₆As₂S₁₁',
    'Petzit': 'Ag₃AuTe₂',
    'Polyargyrit': 'Ag₁₆Sb₂S₁₁',
    'Polybasit': '(Ag,Cu)₁₆Sb₂S₁₁',
    'Proustit': 'Ag₃AsS₃',
    'Pyrargyrit': 'Ag₃SbS₃',
    'Pyrit': 'FeS₂',
    'Pyrrhotin': 'Fe₇S₈',
    'Rammelsbergit': 'NiAs₂',
    'Realgar': 'As₄S₄',
    'Safflorit': 'CoAs₂',
    'Seligmannit': 'PbCuAsS₃',
    'Siegenit': '(Co,Ni)₃S₄',
    'Skutterudit': '(Co,Ni)As₃',
    'Smaltit': 'CoAs₃',
    'Sphalerit': 'ZnS',
    'Stephanit': 'Ag₅SbS₄',
    'Sternbergit': 'AgFe₂S₃',
    'Stibnit': 'Sb₂S₃',
    'Sylvanit': 'AuAgTe₄',
    'Tennantit': 'Cu₁₂As₄S₁₃',
    'Tetraedrit': 'Cu₁₀(Fe,Zn)₂Sb₄S₁₃',
    'Tiemannit': 'HgSe',
    'Ullmannit': 'NiSbS',
    'Umangit': 'Cu₃Se₂',
    'Wittichenit': 'Cu₃BiS₃',
    'Wurzit': 'ZnS',
}

SULFOSALTS = {
    'Baumhauerit': 'Pb₁₂As₁₆S₃₆',
    'Boulangerit': 'Pb₅Sb₄S₁₁',
    'Bournonit': 'PbCuSbS₃',
    'Fahlerz': 'Cu₁₂(Sb,As)₄S₁₃',
    'Falkmanit': 'Pb₃Sb₂S₈',
    'Geocronit': 'Pb₁₄(Sb,As)₆S₂₃',
    'Jamesonit': 'Pb₄FeSb₆S₁₄',
    'Meneghinit': 'Pb₁₃CuSb₇S₂₄',
    'Plagionit': 'Pb₅Sb₈S₁₇',
    'Seligmannit': 'PbCuAsS₃',
    'Semseyit': 'Pb₉Sb₈S₂₁',
}

# =============================================
# CARBONATES
# =============================================
CARBONATES = {

    'Alstonit': 'BaCa(CO₃)₂',
    'Ankerit': 'Ca(Fe,Mg)(CO₃)₂',
    'Apatit': 'Ca₅(PO₄)₃(OH,F,Cl)',
    'Aragonit': 'CaCO₃',
    'Aurichalcit': '(Zn,Cu)₅(CO₃)₂(OH)₆',
    'Azurit': 'Cu₃(CO₃)₂(OH)₂',
    'Barytocalcit': 'BaCa(CO₃)₂',
    'Benstonit': '(Ba,Sr)₆Ca₆Mg(CO₃)₁₃',
    'Cerussit': 'PbCO₃',
    'Chondrodit': 'Mg₅(CO₃)₄(SiO₄)₂(OH)₂',
    'Clinohumit': 'Ca₉Mg(CO₃)₄(SiO₄)₄(OH)₂',
    'Dolomit': 'CaMg(CO₃)₂',
    'Gaylussit': 'Na₂Ca(CO₃)₂·5H₂O',
    'Hydrozinkit': 'Zn₅(CO₃)₂(OH)₆',
    'Kalzit': 'CaCO₃',
    'Magnesit': 'MgCO₃',
    'Malachit': 'Cu₂CO₃(OH)₂',
    'Nahcolit': 'NaHCO₃',
    'Natrit': 'Na₂CO₃',
    'Norbergit': 'Mg₃(CO₃)(SiO₄)(OH)₂',
    'Northupit': 'Na₃Mg(CO₃)₂Cl',
    'Nyerereit': 'Na₂Ca(CO₃)₂',
    'Paratacamit': 'Cu₃(CO₃)₂(OH)₂',
    'Pirssonit': 'Na₂Ca(CO₃)₂·2H₂O',
    'Rhodochrosit': 'MnCO₃',
    'Rosasit': '(Cu,Zn)₂CO₃(OH)₂',
    'Shortit': 'Na₂Ca₂(CO₃)₃',
    'Siderit': 'FeCO₃',
    'Smithsonit': 'ZnCO₃',
    'Strontianit': 'SrCO₃',
    'Tacamit': 'Cu₃(CO₃)₂(OH)₂',
    'Thermonatrit': 'Na₂CO₃·H₂O',
    'Trona': 'Na₃H(CO₃)₂·2H₂O',
    'Tychit': 'Na₆Mg₂(CO₃)₄SO₄',
    'Vaterit': 'CaCO₃',
    'Witherit': 'BaCO₃',
    'Zinkrosasit': 'Zn₂CO₃(OH)₂',
}

# =============================================
# SULFATES & CHROMATES
# =============================================
SULFATES = {
    'Alunit': 'KAl₃(SO₄)₂(OH)₆',
    'Anglesit': 'PbSO₄',
    'Anhydrit': 'CaSO₄',
    'Antlerit': 'Cu₃SO₄(OH)₄',
    'Arseniosiderit': 'Ca₂Fe₃(AsO₄)₃(OH)₃',
    'Baryt': 'BaSO₄',
    'Beudantit': 'PbFe₃(AsO₄,SO₄)₂(OH)₆',
    'Bianchit': '(Zn,Fe)SO₄·6H₂O',
    'Brochantit': 'Cu₄SO₄(OH)₆',
    'Chalcanthit': 'CuSO₄·5H₂O',
    'Chalcocyanit': 'CuSO₄',
    'Coelestin': 'SrSO₄',
    'Conichalcit': 'CaCuAsO₄(OH)',
    'Corkit': 'PbFe₃(PO₄,SO₄)₂(OH)₆',
    'Devillit': 'CaCu₄(SO₄)₂(OH)₆·3H₂O',
    'Duftit': 'PbCuAsO₄(OH)',
    'Epsomit': 'MgSO₄·7H₂O',
    'Gips': 'CaSO₄·2H₂O',
    'Glauberit': 'Na₂SO₄·CaSO₄',
    'Goslarit': 'ZnSO₄·7H₂O',
    'Hexahydrit': 'MgSO₄·6H₂O',
    'Hinsdalit': 'PbAl₃(PO₄,SO₄)₂(OH)₆',
    'Hydroniumjarosit': '(H₃O)Fe₃(SO₄)₂(OH)₆',
    'Jarosit': 'KFe₃(SO₄)₂(OH)₆',
    'Kieserit': 'MgSO₄·H₂O',
    'Kintoreit': 'PbFe₃(PO₄)₂(OH)₆',
    'Ktenasit': 'ZnCu₄(SO₄)₂(OH)₆·2H₂O',
    'Langit': 'Cu₄SO₄(OH)₆·2H₂O',
    'Linarit': 'PbCuSO₄(OH)₂',
    'Melanterit': 'Fe²⁺SO₄·7H₂O',
    'Morenosit': 'NiSO₄·7H₂O',
    'Natrojarosit': 'NaFe₃(SO₄)₂(OH)₆',
    'Pentahydrit': 'MgSO₄·5H₂O',
    'Pentahydrit': 'MgSO₄·5H₂O',
    'Plumbogummit': 'PbAl₃(PO₄)₂(OH)₅·H₂O',
    'Polyhalit': 'K₂SO₄·MgSO₄·2CaSO₄·2H₂O',
    'Posnjakit': 'Cu₄SO₄(OH)₆·H₂O',
    'Retgersit': 'NiSO₄·6H₂O',
    'Sanderit': 'MgSO₄·2H₂O',
    'Schoenit': 'K₂Mg(SO₄)₂·6H₂O',
    'Schultenit': 'PbH₂AsO₄',
    'Sciaccalugit': 'Cu₄Fe(SO₄)₂(OH)₆·2H₂O',
    'Segnitit': 'PbFe₃H₂(AsO₄)₄·8H₂O',
    'Serpierit': 'Ca(Cu,Zn)₄(SO₄)₂(OH)₆·3H₂O',
    'Starkeyit': 'MgSO₄·4H₂O',
    'Susannit': 'Pb₄(SO₄)(CO₃)₂(OH)₂',
    'Thenardit': 'Na₂SO₄',
    'Wroewolfeit': 'Cu₄SO₄(OH)₆·H₂O',
    'Yukonit': 'Ca₇Fe₁₀(AsO₄)₁₂·20H₂O',
}

CHROMATES = {
    'Deanesmithit': 'Hg₂⁺Hg₂²⁺CrO₄S₂',
    'Edoylerit': 'Hg₃CrO₄S₂',
    'Hashemit': 'BaCrO₄',
    'Krokoit': 'PbCrO₄',
    'Lopezit': 'K₂Cr₂O₇',
    'Molybdochroit': 'PbCrO₄·PbMoO₄',
    'Phönikochroit': 'Pb₂O(CrO₄)',
    'Tarapeacit': 'K₂CrO₄',
    'Vauquelinit': 'Pb₂Cu(CrO₄)PO₄(OH)',
}

# =============================================
# PHOSPHATES, ARSENATES, VANADATES
# =============================================
PHOSPHATES = {
    'Adamit': 'Zn₂AsO₄(OH)',
    'Annbergit': 'Ni₃(AsO₄)₂·8H₂O',
    'Apatit': 'Ca₅(PO₄)₃(OH,F,Cl)',
    'Autunit': 'Ca(UO₂)₂[PO₄]₂·10-12H₂O',
    'Barbosalit': 'Fe₂Fe(PO₄)₂(OH)₂',
    'Beraunit': 'Fe₆(PO₄)₄O(OH)₄·6H₂O',
    'Brandtit': 'Ca₂Mn(AsO₄)₂·2H₂O',
    'Brendelit': '(Bi,Pb²⁺)₂(Fe⁴⁺,Fe²⁺)[O₂|OH|PO₄]',
    'Carbonate-Fluorapatit': 'Ca₅(PO₄,CO₃)₃(F,OH)',
    'Chalcosiderit': 'CuFe₆(PO₄)₄(OH)₈·4H₂O',
    'Chernovit': '(Y,Ce)PO₄',
    'Chlorapatit': 'Ca₅(PO₄)₃Cl',
    'Churchit': '(Y,Ce)PO₄·2H₂O',
    'Clinohumit': 'Ca₉Mg(CO₃)₄(SiO₄)₄(OH)₂',
    'Cornubit': 'Cu₅(PO₄)₂(OH)₄',
    'Descloizit': 'Pb(Zn,Cu)VO₄(OH)',
    'Dufrénit': 'Ca₂Fe₅(PO₄)₄(OH)₆·2H₂O',
    'Erythrin': 'Co₃(AsO₄)₂·8H₂O',
    'Eveit': 'Mn₂AsO₄(OH)',
    'Fluorapatit': 'Ca₅(PO₄)₃F',
    'Graftonit': '(Fe,Mn,Ca)₃(PO₄)₂',
    'Heterosit': 'FePO₄',
    'Hureaulit': 'Mn₅(PO₄)₂(VO₄)₂·10H₂O',
    'Hydroxylapatit': 'Ca₅(PO₄)₃(OH)',
    'Hydroxylwagnerit': 'Mg₂(PO₄)(OH)',
    'Kampylit': 'Pb₅[(As,P)O₄]₃Cl',
    'Kidwellit': '(Fe,Mn)₃(PO₄)₂·4H₂O',
    'Köttigit': 'Zn₃(AsO₄)₂·8H₂O',
    'Lazulith': 'MgAl₂(PO₄)₂(OH)₂',
    'Libethenit': 'Cu₂PO₄(OH)',
    'Lipscombit': 'Fe₃Fe(PO₄)₂(OH)₅·2H₂O',
    'Ludlamit': 'Fe₃(PO₄)₂·4H₂O',
    'Mansfieldit': 'AlAsO₄·2H₂O',
    'Metastrengit': 'FePO₄',
    'Metavariscit': 'AlPO₄',
    'Mimetesit': 'Pb₅(AsO₄)₃Cl',
    'Mixit': 'BiCu₆[(OH)₆|(AsO₄)₃]·3H₂O',
    'Monazit': '(Ce,La,Nd,Th)PO₄',
    'Mottramit': 'Pb(Zn,Cu)VO₄(OH)',
    'Namibit': 'Cu²⁺(BiO)₂VO₄OH',
    'Neustädtelit': 'Bi₂Fe³⁺₂O₂(OH)₂(AsO₄)₂',
    'Olivenit': 'Cu₂AsO₄(OH)',
    'Paradamit': 'Zn₂AsO₄(OH)',
    'Parasymplesit': 'Fe₃(AsO₄)₂·8H₂O',
    'Petijeanit': 'Bi₃O(OH)(PO₄)₂',
    'Phosphuranylit': 'KCa(H₃O)₃(UO₂)₇(PO₄)₄O₄·8H₂O',
    'Preisingerit': 'Bi₃(AsO₄)₂₀(OH)',
    'Pucherit': 'BiVO₄',
    'Purpurit': 'MnPO₄',
    'Pyromorphit': 'Pb₅(PO₄)₃Cl',
    'Rhabdophan': '(Y,Ce)PO₄·H₂O',
    'Roselith': '(Ca,Co,Mg)(AsO₄)·2H₂O',
    'Sarkinit': 'Mn₂AsO₄(OH)',
    'Sarkopsid': '(Fe,Mn)₃(PO₄)₂',
    'Schneebergit': 'Bi(Co,Ni)₂(AsO₄)₂(OH,H₂O)₂',
    'Schuhmacherit': 'Bi₃[(V,As,P)O₄]₂O(OH)',
    'Skorodit': 'FeAsO₄·2H₂O',
    'Strengit': 'FePO₄·2H₂O',
    'Svarzit': 'CoAsO₄·2H₂O',
    'Symplesit': 'Fe₃(AsO₄)₂·8H₂O',
    'Torbernit': 'Cu(UO₂)₂[PO₄]₂·12H₂O',
    'Triplit': '(Mn,Fe)₂(PO₄)F',
    'Triploidit': '(Mn,Fe)₂(PO₄)F',
    'Türkis': 'CuAl₆(PO₄)₄(OH)₈·4H₂O',
    'Uranophan': 'Ca(UO₂)₂(SiO₃OH)₂·5H₂O',
    'Vanadinit': 'Pb₅(VO₄)₃Cl',
    'Variscit': 'AlPO₄·2H₂O',
    'Vivianit': 'Fe₃(PO₄)₂·8H₂O',
    'Wagnerit': 'Mg₂(PO₄)F',
    'Walpurgin': 'Bi₄(UO₂)(AsO₄)₂O₄·2H₂O',
    'Wavellit': 'Al₃(PO₄)₂(OH)₃·5H₂O',
    'Weinschenkit': 'YPO₄·2H₂O',
    'Xenotim': 'YPO₄',
    'Zwieselit': '(Fe,Mn)₂(PO₄)F',
    'Zeunerit': 'Cu(UO₂)₂[AsO₄]₂·10-16H₂O',
}

# =============================================
# SILICATES
# =============================================
SILICATES = {
    # Nesosilicates

    'Albit': 'NaAlSi₃O₈',
    'Almandin': 'Fe₃Al₂(SiO₄)₃',
    'Andesin': '(Na,Ca)(Si,Al)₄O₈',
    'Andradit': 'Ca₃Fe₂(SiO₄)₃',
    'Anorthit': 'CaAl₂Si₂O₈',
    'Anorthoklas': '(Na,K)AlSi₃O₈',
    'Axinit': 'Ca₂Al₂BSi₄O₁₅(OH)',
    'Bytownit': '(Na,Ca)(Si,Al)₄O₈',
    'Celsian': 'BaAl₂Si₂O₈',
    'Chrysoberyll': 'BeAl₂O₄',
    'Coffinit': 'USiO₄',
    'Danburit': 'CaB₂(SiO₄)₂',
    'Datolith': 'CaBSiO₄(OH)',
    'Dravit': 'NaMg₃Al₆(B₃Si₆O₂₇)(OH)₄',
    'Elbait': 'Na(Li,Al)₃Al₆(B₃Si₆O₂₇)(OH)₄',
    'Eukryptit': 'LiAlSiO₄',
    'Eulytin': 'Bi₄(SiO₄)₃',
    'Fayalit': 'Fe₂SiO₄',
    'Feldspat': 'KAlSi₃O₈',
    'Forsterit': 'Mg₂SiO₄',
    'Granat': 'X₃Y₂(SiO₄)₃',
    'Grossular': 'Ca₃Al₂(SiO₄)₃',
    'Hibschit': 'Ca₃Al₂(SiO₄)(OH)₄',
    'Huttonit': 'ThSiO₄',
    'Hyalophan': '(K,Ba)Al(Si,Al)₃O₈',
    'Hydrogrossular': 'Ca₃Al₂(SiO₄)₃-2x(OH)₄x',
    'Katoit': 'Ca₃Al₂(SiO₄)(OH)₄',
    'Labradorit': '(Ca,Na)(Al,Si)₄O₈',
    'Larnit': 'Ca₂SiO₄',
    'Liddicoatit': 'Ca(Li,Al)₃Al₅(B₃Si₆O₂₇)(OH)₄',
    'Mikroklin': 'KAlSi₃O₈',
    'Oligoklas': '(Na,Ca)(Si,Al)₄O₈',
    'Oligoklas': '(Na,Ca)(Si,Al)₄O₈',
    'Olive': '(Mg,Fe)₂SiO₄',
    'Orthoklas': 'KAlSi₃O₈',
    'Phenakit': 'Be₂SiO₄',
    'Pyrop': 'Mg₃Al₂(SiO₄)₃',
    'Sanidin': 'KAlSi₃O₈',
    'Schorl': 'NaFe₃Al₆(B₃Si₆O₂₇)(OH)₄',
    'Spessartin': 'Mn₃Al₂(SiO₄)₃',
    'Sphen': 'CaTiSiO₅',
    'Staurolith': 'Fe₂Al₉O₆(SiO₄)₄(O,OH)₂',
    'Tephroit': 'Mn₂SiO₄',
    'Thorit': 'ThSiO₄',
    'Titanit': 'CaTiSiO₅',
    'Topas': 'Al₂SiO₄(F,OH)₂',
    'Tourmalin': 'Complex',
    'Uvarovit': 'Ca₃Cr₂(SiO₄)₃',
    'Uvit': 'CaMg₃Al₅(B₃Si₆O₂₇)(OH)₄',
    'Willemit': 'Zn₂SiO₄',
    'Zirkon': 'ZrSiO₄',
    # Sorosilicates

    'Allanit': 'Ca(Ce,La,Y,Ca)Al₂(Fe²⁺,Fe³⁺)(SiO₄)(Si₂O₇)O(OH)',
    'Beryll': 'Be₃Al₂(SiO₃)₆',
    'Clinozoisit': 'Ca₂Al₃(SiO₄)(Si₂O₇)O(OH)',
    'Cordierit': '(Mg,Fe)₂Al₄Si₅O₁₈·nH₂O',
    'Epidot': 'Ca₂Al₂(Fe,Al)(SiO₄)(Si₂O₇)O(OH)',
    'Hemimorphit': 'Zn₄Si₂O₇(OH)₂·H₂O',
    'Ilvait': 'CaFe₂FeSi₂O₈(OH)',
    'Lawsonit': 'CaAl₂Si₂O₇(OH)₂·H₂O',
    'Sekaninait': 'Fe₂Al₄Si₅O₁₈·nH₂O',
    'Vesuvianit': 'Ca₁₀Mg₂Al₄(SiO₄)₅(Si₂O₇)₂(OH)₄',
    'Zoisit': 'Ca₂Al₃(SiO₄)(Si₂O₇)O(OH)',
    # Cyclosilicates

    'Beryll': 'Be₃Al₂(SiO₃)₆',
    'Turmalin': 'Complex',
    # Inosilicates (Single chain)

    'Aegirin': 'NaFeSi₂O₆',
    'Aktinolith': 'Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂',
    'Anthophyllit': 'Mg₇Si₈O₂₂(OH)₂',
    'Augit': '(Ca,Na)(Mg,Fe,Al)(Si,Al)₂O₆',
    'Bronzit': '(Mg,Fe)SiO₃',
    'Bustamit': '(Ca,Mn)SiO₃',
    'Cummingtonit': 'Fe₂Mg₅Si₈O₂₂(OH)₂',
    'Diopsid': 'CaMgSi₂O₆',
    'Enstatit': 'MgSiO₃',
    'Ferrosilit': 'FeSiO₃',
    'Gedrit': 'Mg₅Al₂Si₆O₁₈(OH)₂',
    'Grunerit': 'Fe₇Si₈O₂₂(OH)₂',
    'Hedenbergit': 'CaFeSi₂O₆',
    'Holmquistit': 'Li₂Mg₃Al₂Si₈O₂₂(OH)₂',
    'Hornblende': 'Ca₂(Mg,Fe,Al)₅(Si,Al)₈O₂₂(OH)₂',
    'Hypersthen': '(Mg,Fe)SiO₃',
    'Jadeit': 'NaAlSi₂O₆',
    'Johannsenit': 'CaMnSiO₃',
    'Kanoit': 'MnMgSiO₃',
    'Namansilit': 'NaMnSiO₃',
    'Pektolith': 'NaCa₂Si₃O₈(OH)',
    'Pigeonit': '(Ca,Mg,Fe)(Mg,Fe)Si₂O₆',
    'Pyroxmangit': 'MnSiO₃',
    'Rhodonit': 'MnSiO₃',
    'Spodumen': 'LiAlSi₂O₆',
    'Tremolit': 'Ca₂Mg₅Si₈O₂₂(OH)₂',
    'Wollastonit': 'CaSiO₃',
    # Inosilicates (Double chain)

    'Brewsterit': '(Sr,Ba,Ca)Al₄Si₈O₂₄·10H₂O',
    'Chabasit': '(Ca,Na₂,K₂)Al₂Si₄O₁₂·6H₂O',
    'Epistilbit': 'Ca₃Al₆Si₁₀O₃₂·14H₂O',
    'Gmelinit': '(Na,K)₄Al₄Si₈O₂₄·11H₂O',
    'Gonnardit': '(Na,Ca)₆Al₈Si₁₀O₃₆·12H₂O',
    'Harmotom': 'Ba₂Al₄Si₁₂O₃₂·12H₂O',
    'Heulandit': '(Ca,Na)₅Al₉Si₂₇O₇₂·24H₂O',
    'Mordenit': '(Ca,Na₂,K₂)Al₂Si₁₀O₂₄·7H₂O',
    'Phillipsit': '(K,Na,Ca)₄Al₄Si₈O₂₄·12H₂O',
    'Stilbit': 'NaCa₄Al₈Si₂₈O₇₂·28H₂O',
    # Phyllosilicates (Sheet silicates)

    'Antigorit': 'Mg₃Si₂O₅(OH)₄',
    'Beidellit': '(Na,Ca)₀.₃₃Al₂(Al,Si)₄O₁₀(OH)₂·nH₂O',
    'Biotit': 'K(Mg,Fe)₃AlSi₃O₁₀(OH)₂',
    'Chamosit': '(Fe,Mg)₅Al(Si,Al)₄O₁₀(OH)₈',
    'Chlorit': '(Mg,Fe)₃(Si,Al)₄O₁₀(OH)₂·(Mg,Fe)₃(OH)₆',
    'Chrysokoll': '(Cu,Al)₂H₂Si₂O₅(OH)₄ · nH₂O',
    'Chrysotil': 'Mg₃Si₂O₅(OH)₄',
    'Clinochlor': '(Mg,Fe)₅Al(Si,Al)₄O₁₀(OH)₈',
    'Cookeit': 'LiAl₄(Si,Al)₄O₁₀(OH)₈',
    'Dickit': 'Al₂Si₂O₅(OH)₄',
    'Fuchsit': 'K(Al,Cr)₂(Al,Cr)Si₃O₁₀(OH)₂',
    'Glimmer': 'KAl₂(AlSi₃O₁₀)(OH)₂',
    'Halloyit': 'Al₂Si₂O₅(OH)₄·2H₂O',
    'Illit': 'K₀.₆₅Al₂(Al,Si)₄O₁₀(OH)₂',
    'Kaolinit': 'Al₂Si₂O₅(OH)₄',
    'Lepidolith': 'K(Li,Al)₂-₃(Al,Si)₄O₁₀(OH)₂',
    'Lizardit': 'Mg₃Si₂O₅(OH)₄',
    'Montmorillonit': '(Na,Ca)₀.₃₃(Al,Mg)₂Si₄O₁₀(OH)₂·nH₂O',
    'Muskovit': 'KAl₂(AlSi₃O₁₀)(OH)₂',
    'Nakrit': 'Al₂Si₂O₅(OH)₄',
    'Nimit': '(Ni,Mg,Fe)₅Al(Si,Al)₄O₁₀(OH)₈',
    'Nontronit': '(Na,Ca)₀.₃₃Fe₂(Al,Si)₄O₁₀(OH)₂·nH₂O',
    'Paragonit': 'NaAl₂(AlSi₃O₁₀)(OH)₂',
    'Pennin': '(Mg,Fe)₅Al(Si,Al)₄O₁₀(OH)₈',
    'Phlogopit': 'KMg₃AlSi₃O₁₀(OH)₂',
    'Pyrophyllit': 'Al₂Si₄O₁₀(OH)₂',
    'Saponit': '(Ca/2,Na,K)₀.₃₃(Mg,Fe)₃(Al,Si)₄O₁₀(OH)₂·nH₂O',
    'Serpentin': 'Mg₃Si₂O₅(OH)₄',
    'Sudoit': 'Mg₅Al(Si,Al)₄O₁₀(OH)₈',
    'Talck': 'Mg₃Si₄O₁₀(OH)₂',
    'Talk': 'Mg₃Si₄O₁₀(OH)₂',
    'Vermiculit': '(Mg,Fe,Al)₃(Al,Si)₄O₁₀(OH)₂·4H₂O',
    'Zinnwaldit': 'K(Li,Fe,Al)₂-₃(Al,Si)₄O₁₀(OH)₂',
    # Tektosilicates (Framework silicates)
    'Achat': 'SiO₂',
    'Albit': 'NaAlSi₃O₈',
    'Analcim': 'NaAlSi₂O₆·H₂O',
    'Anorthit': 'CaAl₂Si₂O₈',
    'Anorthoklas': '(Na,K)AlSi₃O₈',
    'Cancrinit': 'Na₆Ca₂Al₆Si₆O₂₄(CO₃)₂',
    'Celsian': 'BaAl₂Si₂O₈',
    'Chalcedon': 'SiO₂',
    'Chrysopras': 'SiO₂',
    'Coesit': 'SiO₂',
    'Cristobalit': 'SiO₂',
    'Davyn': '(Na,K)₆Ca₂Al₆Si₆O₂₄Cl₂',
    'Feldspat': 'KAlSi₃O₈',
    'Gonnardit': '(Na,Ca)₆Al₈Si₁₀O₃₆·12H₂O',
    'Hauyn': '(Na,K)₈Al₆Si₆O₂₄(SO₄)₂',
    'Helvin': 'Mn₄Be₃(SiO₄)₃S',
    'Hyalophan': '(K,Ba)Al(Si,Al)₃O₈',
    'Laumontit': 'CaAl₂Si₄O₁₂·4H₂O',
    'Lazurit': 'Na₈Al₆Si₆O₂₄S₆',
    'Lechatelierit': 'SiO₂',
    'Leonhardit': 'CaAl₂Si₄O₁₂·4H₂O',
    'Leucit': 'KAlSi₂O₆',
    'Marialit': 'Na₈Al₆Si₆O₂₄Cl₂',
    'Meionit': 'Ca₈Al₆Si₆O₂₄CO₃',
    'Mesolit': 'Na₁₆Al₁₆Si₂₄O₈₀·16H₂O',
    'Mikroklin': 'KAlSi₃O₈',
    'Natrolit': 'Na₁₆Al₁₆Si₂₄O₈₀·16H₂O',
    'Nephelin': '(Na,K)AlSiO₄',
    'Nosean': 'Na₈Al₆Si₆O₂₄SO₄',
    'Orthoklas': 'KAlSi₃O₈',
    'Pollucit': '(Cs,Na)AlSi₂O₆·H₂O',
    'Quarz': 'SiO₂',
    'Sanidin': 'KAlSi₃O₈',
    'Scapolith': '(Na,Ca)₈Al₆Si₆O₂₄(Cl,CO₃,SO₄)₂',
    'Scolecit': 'CaAl₂Si₃O₁₀·3H₂O',
    'Sodalith': 'Na₈Al₆Si₆O₂₄Cl₂',
    'Stishovit': 'SiO₂',
    'Thomsonit': '(Na,Ca)₈Al₈Si₁₆O₅₆·24H₂O',
    'Tridymit': 'SiO₂',
    'Vishnevit': 'Na₆Ca₂Al₆Si₆O₂₄(SO₄)₂',
    'Wairakit': 'CaAl₂Si₄O₁₂·2H₂O',
    'Yugawaralit': 'CaAl₂Si₆O₁₆·4H₂O',
    'Zeolith': 'General term',
    # Amorphe Varietaeten
    'Hyalit': 'SiO₂ * nH₂O',
    'Opal': 'SiO₂ * nH₂O',
}

# =============================================
# BORATES
# =============================================
BORATES = {
    'Ascharit': 'MgHBO₃',
    'Borax': 'Na₂B₄O₇·10H₂O',
    'Colemanit': 'Ca₂B₆O₁₁·5H₂O',
    'Fabianit': 'CaB₆O₁₀·4H₂O',
    'Ginorit': 'Ca₂B₁₄O₂₃·8H₂O',
    'Howlith': 'Ca₂B₅SiO₉(OH)',
    'Inyoit': 'Ca₂B₆O₁₁·13H₂O',
    'Kernit': 'Na₂B₄O₇·4H₂O',
    'Kotoit': 'Mg₃B₂O₅',
    'Londaleit': 'MgB₃O₃(OH)₃·H₂O',
    'Lüneburgit': 'Mg₃B₂(PO₄)₂(OH)₂',
    'Meyerhofferit': 'Ca₂B₆O₁₁·7H₂O',
    'Nobleit': 'CaB₆O₁₀·4H₂O',
    'Pandermit': 'Ca₄B₁₀O₁₉·7H₂O',
    'Pinnoit': 'MgB₂O₄',
    'Priceit': 'Ca₄B₁₀O₁₉·7H₂O',
    'Probertit': 'NaCaB₅O₉·5H₂O',
    'Rhodizit': '(K,Cs)Al₄Be₄B₁₁O₂₈',
    'Sassolit': 'B(OH)₃',
    'Seamanit': 'Mn₃B₂(PO₄)₂(OH)₂',
    'Sinhalit': 'MgAlBO₄',
    'Suanit': 'Mg₂B₂O₅',
    'Szaibélyit': 'MgBO₂(OH)',
    'Tincalconit': 'Na₂B₄O₇·5H₂O',
    'Tunellit': 'SrB₆O₁₀·4H₂O',
    'Ulexit': 'NaCaB₅O₉·8H₂O',
    'Veatchit': 'Sr₂B₁₁O₁₉·8H₂O',
    'Warwickit': 'Mg(Ti,Al)BO₄',
}

# =============================================
# TUNGSTATES & MOLYBDATES
# =============================================
TUNGSTATES_MOLYBDATES = {
    'Anthoinit': 'AlWO₄(OH)',
    'Coquinbit': 'Fe₂(MoO₄)₃·8H₂O',
    'Cuproscheelit': 'CuWO₄',
    'Ferberit': 'FeWO₄',
    'Ferrimolybdit': 'Fe₂(MoO₄)₃·8H₂O',
    'Hübnerit': 'MnWO₄',
    'Ilesit': '(Mn,Fe)(Nb,Ta)₂O₆',
    'Lindgrenit': 'Cu₃(MoO₄)₂(OH)₂',
    'Powellit': 'CaMoO₄',
    'Raspit': 'PbWO₄',
    'Sanmartinit': 'ZnWO₄',
    'Scheelit': 'CaWO₄',
    'Sedovit': 'U(MoO₄)₂',
    'Stolzit': 'PbWO₄',
    'Umohoit': '(UO₂)MoO₄·4H₂O',
    'Wolframit': '(Fe,Mn)WO₄',
    'Wulfenit': 'PbMoO₄',
}

# =============================================
# HALIDES
# =============================================
HALIDES = {
    'Atacamit': 'Cu₂Cl(OH)₃',
    'Boleit': 'KPb₂₆Ag₉Cu₂₄Cl₆₂(OH)₄₈',
    'Botallackit': 'Cu₂Cl(OH)₃',
    'Bromargyrit': 'AgBr',
    'Calciumchlorid': 'CaCl₂',
    'Calomel': 'Hg₂Cl₂',
    'Carnallit': 'KMgCl₃·6H₂O',
    'Chalkomenit': 'CuSeO₃·2H₂O',
    'Chiolith': 'Na₅Al₃F₁₄',
    'Chlorargyrit': 'AgCl',
    'Clinoatacamit': 'Cu₂Cl(OH)₃',
    'Compreignacit': 'K₂HgCl₄',
    'Cotunnit': 'PbCl₂',
    'Cryolith': 'Na₃AlF₆',
    'Cumengit': 'Pb₁₆Cu₉Cl₄₆(OH)₄₀',
    'Diaboleit': 'Pb₂CuCl₂(OH)₄',
    'Eglestonit': 'Hg₆Cl₃O',
    'Fiedlerit': 'Pb₃Cl₄F(OH)₂',
    'Fluorit': 'CaF₂',
    'Gearksutit': 'CaAlF₅·H₂O',
    'Halit': 'NaCl',
    'Iodargyrit': 'AgI',
    'Kainit': 'KMg(SO₄)Cl·3H₂O',
    'Kelyanit': 'Hg₅Cl₂O₂',
    'Kieserit': 'MgSO₄·H₂O',
    'Laurionit': 'PbCl(OH)',
    'Marshit': 'CuI',
    'Matlockit': 'PbFCl',
    'Mendipit': 'Pb₃Cl₂O₂',
    'Miersit': '(Ag,Cu)I',
    'Mosesit': '(Hg₂N)Cl·H₂O',
    'Nantokit': 'CuCl',
    'Pachnolith': 'NaCaAlF₆·H₂O',
    'Paralaurionit': 'PbCl(OH)',
    'Paratacamit': 'Cu₂Cl(OH)₃',
    'Penfieldit': 'PbCl(OH)',
    'Phosgenit': 'Pb₂CO₃Cl₂',
    'Prosopit': 'CaAl₂F₈·H₂O',
    'Ralstonit': 'NaMgAlF₆·H₂O',
    'Sylvin': 'KCl',
    'Terlinguait': 'Hg₂OCl',
    'Thomsenolith': 'NaCaAlF₆·H₂O',
    'Weberit': 'Na₂MgAlF₇',
}

# =============================================
# COMPLETE DICTIONARY
# =============================================
# Combine all dictionaries into one
COMMON_MINERALS = {}
COMMON_MINERALS.update(NATIVE_ELEMENTS)
COMMON_MINERALS.update(OXIDES_HYDROXIDES)
COMMON_MINERALS.update(SULFIDES)
COMMON_MINERALS.update(SULFOSALTS)
COMMON_MINERALS.update(CARBONATES)
COMMON_MINERALS.update(SULFATES)
COMMON_MINERALS.update(CHROMATES)
COMMON_MINERALS.update(PHOSPHATES)
COMMON_MINERALS.update(SILICATES)
COMMON_MINERALS.update(BORATES)
COMMON_MINERALS.update(TUNGSTATES_MOLYBDATES)
COMMON_MINERALS.update(HALIDES)

def get_formula(mineral_name):
    """
    Get chemical formula for a mineral name.
    Case-insensitive lookup with partial matching.
    """
    if not mineral_name or not mineral_name.strip():
        return None

    mineral_name = mineral_name.strip().title()

    # Direct match
    if mineral_name in COMMON_MINERALS:
        return COMMON_MINERALS[mineral_name]

    # Case-insensitive match
    for key, value in COMMON_MINERALS.items():
        if mineral_name.lower() == key.lower():
            return value

    # Partial matching (mineral name contains key or vice versa)
    for key, value in COMMON_MINERALS.items():
        if (mineral_name.lower() in key.lower()) or (key.lower() in mineral_name.lower()):
            return value

    # No match found
    return None
